name: 'Integration Tests'

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Start Anvil Server
        run: pnpm anvil --fork-url https://eth.merkle.io
      - name: Run tests
        run: pnpm run test:integration
